services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: sh -c "alembic upgrade head && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django-app/main/uwsgi_params:/usr/share/nginx/uwsgi_params:ro
      - ./django-app/static:/usr/share/nginx/static
      - ./django-app/media:/usr/share/nginx/media
      - ./docker/socket:/usr/share/nginx/socket
    ports:
      - "80:8080"
    depends_on:
      - backend
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    image: bank-frontend:latest
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"
volumes:
  pg-data: {}
