volumes:
  pg-data:
  media_volume:

services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "8000"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: always
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./backend:/app
      - media_volume:/var/www/media
    depends_on:
      - db
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - VITE_API_URL=/api/v1/
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    depends_on:
      - backend
    expose:
      - "5173"

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - media_volume:/var/www/media
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    depends_on:
      - backend
      - frontend

