services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $BANK_POSTGRESS_PASSWORD
    volumes: 
      - pg-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/django-app/Dockerfile
    command: >
      bash -c "
      uv run manage.py collectstatic --noinput &&
      uv run manage.py makemigrations &&
      uv run manage.py migrate &&
      uv run manage.py runserver 0.0.0.0:8000
      "
#      uv run gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file: .env
    volumes:
      - ./docker/socket:/usr/src/django-app/socket
      - ./docker/django-app/logs:/usr/src/django-app/logs
    depends_on:
      - db
    ports:
        - 8000:8000

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django-app/main/uwsgi_params:/usr/share/nginx/uwsgi_params:ro
      - ./django-app/static:/usr/share/nginx/static
      - ./django-app/media:/usr/share/nginx/media
      - ./docker/socket:/usr/share/nginx/socket
    ports:
      - 80:8080
    depends_on:
      - web
      - db
volumes:
    pg-data: