# Generated by Django 5.1.6 on 2025-06-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('readable_name', models.CharField(max_length=511)),
                ('group_general', models.CharField(blank=True, max_length=31, null=True)),
                ('group_local', models.CharField(blank=True, max_length=31, null=True)),
                ('readable_group_local', models.CharField(default='Other', max_length=127)),
                ('readable_group_general', models.CharField(default='Other', max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('readable_name', models.CharField(max_length=511)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('middle_name', models.CharField(default='Not stated', max_length=40)),
                ('party', models.IntegerField(default=0)),
                ('grade', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('readable_name', models.CharField(max_length=511)),
                ('counted', models.BooleanField(default=False)),
                ('possible_transitions', models.ManyToManyField(to='bank.transactionstate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_map', models.CharField(max_length=262143)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('update_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.transaction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.transactionstate')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('atomictransactiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bank.atomictransactiontype')),
                ('related_transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_attendance', to='bank.transactiontype')),
            ],
            options={
                'abstract': False,
            },
            bases=('bank.atomictransactiontype',),
        ),
        migrations.CreateModel(
            name='AttendanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('readable_name', models.CharField(max_length=511)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('related_attendance_types', models.ManyToManyField(related_name='related_attendance_blocks', to='bank.attendancetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_timestamp', models.DateTimeField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('value', models.FloatField(default=0)),
                ('counted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_attendance', to=settings.AUTH_USER_MODEL)),
                ('attendance_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='bank.attendanceblock')),
                ('related_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_attendance_atomics', to='bank.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.attendancetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyType',
            fields=[
                ('atomictransactiontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bank.atomictransactiontype')),
                ('related_transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_money', to='bank.transactiontype')),
            ],
            options={
                'abstract': False,
            },
            bases=('bank.atomictransactiontype',),
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_timestamp', models.DateTimeField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('value', models.FloatField(default=0)),
                ('counted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_money', to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_money_atomics', to='bank.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.moneytype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
